package database.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import database.LocalCity;

import database.dao.LocalCityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig localCityDaoConfig;

    private final LocalCityDao localCityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        localCityDaoConfig = daoConfigMap.get(LocalCityDao.class).clone();
        localCityDaoConfig.initIdentityScope(type);

        localCityDao = new LocalCityDao(localCityDaoConfig, this);

        registerDao(LocalCity.class, localCityDao);
    }
    
    public void clear() {
        localCityDaoConfig.getIdentityScope().clear();
    }

    public LocalCityDao getLocalCityDao() {
        return localCityDao;
    }

}
